language: node_js
node_js:
  - "lts/*"
dist: trusty
sudo: required
git:
  # Desactivar la verificación del certificado SSL
  # para evitar el error "server certificate verification failed"
  depth: false
branches:
  only:
    - pivot
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  # No verificar el certificado SSL
  - config --global http.sslVerify false
  - npm install
script:
  - ng test --watch=false --browsers=ChromeHeadless
  
# Notificaciones de resultado de compilación
notifications:
  email:
    recipients:
      - ralvarez@kreilabs.com
    on_success: always # siempre notificar cuando la compilación tiene éxito
    on_failure: always # siempre notificar cuando la compilación falla
