language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
git:
  # Desactivar la verificación del certificado SSL
  # para evitar el error "server certificate verification failed"
  depth: false
branches:
  only:
    - pivot
addons:
  chrome: stable
before_install:
  # No verificar el certificado SSL
  - git config --global http.sslVerify false
  - npm install -g @angular/cli
  # apt-get update
  #apt-get install -y ca-certificates
  #export GIT_SSL_NO_VERIFY=true
  #npm config set progress false
install:
  - npm install
script:
  - npm run lint
  - npm run test
  
# Notificaciones de resultado de compilación
notifications:
  email:
    recipients:
      - ralvarez@kreilabs.com
    on_failure: always # siempre notificar cuando la compilación falla
