language: node_js
node_js:
  - "lts/*"
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - ng test --watch=false --browsers=ChromeHeadless
